#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
ROUND3="$ROOT/../open_problem_forr4_passive_floor_consolidation_round_3"
PYTHON_BIN="${PYTHON_BIN:-python3}"

if ! "$PYTHON_BIN" -c 'import numpy, scipy, sympy' >/dev/null 2>&1; then
  printf 'NumPy, SciPy, and SymPy are required under %s; set PYTHON_BIN explicitly.\n' "$PYTHON_BIN" >&2
  exit 2
fi

PYTHON_BIN="$PYTHON_BIN" PYTHONDONTWRITEBYTECODE=1 "$ROUND3/run_round3_checks.sh"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/initialization_check.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/finite_size_passive_ledger.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/opposite_endpoint_correlated_mixture.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/opposite_endpoint_two_axis_mixture.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/signed_permutation_link_moment.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/joint_impact_sparse_q4.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/shared_frontier_structure.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/shared_frontier_row_orbit.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_paper_target_gate.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_block_coherent_contraction.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_chain_aware_insertion.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_remaining_class_gates.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_universal_septimic_insertion.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_universal_multicubic_insertion.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_post_universal_quintic_gate.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_shifted_middle_pair_contraction.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_reversed_middle_pair_contraction.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_fixed_singleton_pair_contraction.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_universal_double_cubic_insertion.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_fixed_pair_adjacent_row_contraction.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_dual_endpoint_schur_insertion.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_dual_endpoint_independent_audit.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_decorated_adjacent_row_insertion.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_degree_ten_completion_row_insertion.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_whole_cubic_decorated_row_insertion.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_last_degree_ten_chain_insertion.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_internal_whole_cubic_endpoint_insertion.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_balanced_pair_triple_mask_insertion.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_adjacent_double_cubic_quintic_endpoint_insertion.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_shared_quintic_acceptance_gate.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_shared_quintic_row_chain_insertion.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_noncubic_recovered_universal_insertion.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_whole_higher_split_cubic_insertion.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_same_side_whole_link_insertion.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/active_six_resource_row.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/active_six_robustness_gate.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_experimental_feasibility_gate.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_paper_closeout_package.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/quadratic_bent_replacement_screen.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_masked_quintic_slice_repair.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_masked_local_walsh_repair.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_masked_cubic_endpoint_repair.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_masked_double_quintic_endpoint_repair.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_masked_double_quintic_record_repair.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_masked_four_cubic_incidence_repair.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_masked_cubic_septimic_chain_repair.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_masked_recovered_cubic_quintic_incidence_repair.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_recovered_cubic_quintic_independent_audit.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_joint_recovered_cubic_quintic_contraction.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_final_residual_chain_contraction.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q8_masked_separated_quintic_residual_screen.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_masked_universal_audit.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_complete_outward_ledger.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_adaptive_interface_gate.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/q64_adaptive_tree_frontier.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/masked_translation_covariance.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/masked_translation_cocycle_inventory.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/masked_translation_full_group_screen.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/masked_translation_subspace_screen.py"
PYTHONDONTWRITEBYTECODE=1 "$PYTHON_BIN" "$ROOT/tests/masked_translation_mixture_screen.py"

printf '%s\n' "PASS round-four regressions; 888/888 balanced entries certified; number-sector-incoherent adaptive frontier multiplier one; passive hard dose six excluded at N=4096 in the restricted class; cross-number-sector extension open; current-platform experimental credibility not certified"
